# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Devin Bunch
url: https://devinbunch.com
github: [metadata]
email: devinespanol@gmail.com
description: >- # this means to ignore newlines in the text below
  Devin Bunch's personal website.
twitter_username: Dev_Bunch
github_username: devinbunch
minimal_mistakes_skin: "default" #"default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /blog/page:num
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Devin"
  avatar : "/assets/images/stairs.jpg"
  bio    : 
    Assistant Prof. at the University of Oregon. 
    Interested in environmental economics & data science.
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://devinbunch.com"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:devinespanol@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Dev_Bunch"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/devinbunch"
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/grant_mcdermott"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/grantmcdermott"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

# Social
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#twitter-cards-and-facebook-open-graph
og_image: /assets/images/default-thumb.png

# Analytics
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-76482472-1"
    anonymize_ip: false # default
